"""
Source data models for the Veridian IT Service Agent.

These models represent data directly supplied by the Data Pack:
- Policies from the knowledge base
- Employee requests
- Existing tickets

SOURCE DATA should not be modified or augmented with unsupported information.
"""

from pydantic import BaseModel, ConfigDict, Field
from typing import Optional


class Policy(BaseModel):
    """
    Policy record from the knowledge base or policy extracts.
    
    This is SOURCE DATA - directly from the supplied Data Pack.
    Do not add business fields not present in the source.
    """
    id: str = Field(..., description="Policy ID (e.g., KB-01, ASSET-01)")
    title: str = Field(..., description="Policy title")
    category: str = Field(..., description="Policy category")
    content: str = Field(..., description="Full policy text as supplied")
    source_type: str = Field(..., description="Type: knowledge_base or policy_extract")
    
    model_config = ConfigDict(frozen=True)  # Immutable - source data should not change


class EmployeeRequest(BaseModel):
    """
    Employee IT support request.
    
    This is SOURCE DATA - directly from the supplied Data Pack.
    Do not add fields like department, employee_type, priority, or severity
    unless they are explicitly present in the source.
    """
    request_id: str = Field(..., description="Request ID (e.g., REQ-01)")
    employee: str = Field(..., description="Employee name")
    email: str = Field(..., description="Employee email address")
    date_opened: str = Field(..., description="Date request was opened")
    request: str = Field(..., description="Full request text as supplied")
    initial_action_taken: str = Field(..., description="Initial action status")
    
    model_config = ConfigDict(frozen=True)  # Immutable - source data should not change


class Ticket(BaseModel):
    """
    Existing ticket from the ticket queue.
    
    This is SOURCE DATA - directly from the supplied Data Pack.
    Status is preserved exactly as supplied.
    """
    ticket_id: str = Field(..., description="Ticket ID (e.g., TK-1042)")
    employee: str = Field(..., description="Employee name")
    issue_summary: str = Field(..., description="Brief issue description")
    status: str = Field(..., description="Ticket status as supplied")
    
    model_config = ConfigDict(frozen=True)  # Immutable - source data should not change


class AuditEvent(BaseModel):
    """
    System-generated audit event.
    
    This is SYSTEM DATA - generated by the application for tracking
    and compliance purposes.
    """
    event_type: str = Field(..., description="Type of audit event")
    timestamp: str = Field(..., description="ISO timestamp of the event")
    request_id: Optional[str] = Field(None, description="Associated request ID if applicable")
    details: dict = Field(default_factory=dict, description="Additional event details")
