"""
Response Generator Module

Uses Gemini LLM to generate natural language responses from AgentDecision objects.
CRITICAL: The LLM only generates message text. The decision value is NEVER changed.
"""

import os
from typing import Optional

from google import genai
from google.genai import types

from app.agent.schemas import AgentDecision, AgentResponse


# Default model configuration
DEFAULT_GEMINI_MODEL = "gemini-3.5-flash-lite"


def generate_response(
    decision: AgentDecision,
    api_key: Optional[str] = None,
    model_name: Optional[str] = None
) -> AgentResponse:
    """
    Generate a natural language response from an AgentDecision.
    
    The LLM generates ONLY the message text. The decision, confidence, and
    reasoning are preserved exactly as provided by the decision engine.
    
    Args:
        decision: AgentDecision from the decision engine (authoritative)
        api_key: Google API key for Gemini (defaults to GEMINI_API_KEY env var)
        model_name: Gemini model to use (defaults to GEMINI_MODEL env var)
    
    Returns:
        AgentResponse with natural language message and preserved decision
    
    Raises:
        ValueError: If API key is missing
    """
    # Get API key
    api_key = api_key or os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY environment variable is required")
    
    # Get model name
    model_name = model_name or os.getenv("GEMINI_MODEL", DEFAULT_GEMINI_MODEL)
    
    # Build prompt that instructs LLM to generate message text only
    prompt = f"""You are an IT support assistant. Generate a professional, friendly response message based on this decision.

DECISION: {decision.decision}
CONFIDENCE: {decision.confidence}
REASONING: {decision.reason}
ACTIONS: {', '.join(decision.actions)}

Your task:
1. Write a natural, professional message for the user
2. Explain the decision clearly and helpfully
3. Include any relevant next steps or guidance
4. Keep the tone friendly and supportive

CRITICAL RULES:
- You are ONLY generating the message text
- DO NOT change the decision ({decision.decision})
- DO NOT add new reasoning or override the provided reasoning
- Simply explain the decision in a user-friendly way

Generate the response message now:"""
    
    try:
        # Initialize Gemini client
        client = genai.Client(api_key=api_key)
        
        # Call Gemini to generate message
        response = client.models.generate_content(
            model=model_name,
            contents=prompt
        )
        
        # Extract message text
        message = response.text.strip() if response and response.text else ""
        
        if not message:
            raise ValueError("LLM returned empty message")
        
        # Return AgentResponse with preserved decision
        return AgentResponse(
            decision=decision.decision,  # PRESERVED from decision engine
            message=message,             # Generated by LLM
            sources=decision.sources,    # PRESERVED
            follow_up_questions=decision.missing_information  # PRESERVED
        )
    
    except Exception as e:
        # Fallback: deterministic response if LLM fails
        # This ensures the business decision is still communicated
        fallback_message = _generate_fallback_message(decision)
        
        return AgentResponse(
            decision=decision.decision,
            message=fallback_message,
            sources=decision.sources,
            follow_up_questions=decision.missing_information
        )


def _generate_fallback_message(decision: AgentDecision) -> str:
    """
    Generate a deterministic fallback message when LLM fails.
    Ensures the business decision is still communicated to the user.
    """
    decision_value = decision.decision
    reasoning = decision.reason
    
    if decision_value == "RESOLVE":
        return f"Your request can be resolved. {reasoning}"
    elif decision_value == "ESCALATE":
        return f"Your request requires escalation to IT support. {reasoning}"
    elif decision_value == "FOLLOW_UP":
        return f"We need more information to process your request. {reasoning}"
    else:
        return f"Decision: {decision_value}. {reasoning}"
