"""
Tests for Decision Engine

Tests the deterministic policy enforcement logic against the actual Data Pack policies.
NO INVENTED RULES. Only what KB-01 through KB-10 and ASSET-01 explicitly state.
"""

import pytest
from app.agent.schemas import (
    ExtractedFacts,
    PolicyEvidence,
    TicketContext,
)
from app.agent.decision_engine import evaluate_decision


# ============================================================================
# Policy Fixtures - Use ACTUAL policy content from Data Pack
# ============================================================================

@pytest.fixture
def kb01_policy():
    """KB-01: Password Reset"""
    return PolicyEvidence(
        policy_id="KB-01",
        title="Password Reset",
        content="Employees can reset their own password via the self-service portal at any time. If locked out after 5 failed attempts, contact IT to unlock the account manually. No approval required.",
        relevance=0.95,
    )


@pytest.fixture
def kb02_policy():
    """KB-02: VPN Access"""
    return PolicyEvidence(
        policy_id="KB-02",
        title="VPN Access",
        content="VPN access is granted automatically to all full-time employees. Contractors require manager approval submitted via the access request form. VPN credentials expire every 90 days and must be renewed by the employee.",
        relevance=0.95,
    )


@pytest.fixture
def kb03_policy():
    """KB-03: Laptop Replacement"""
    return PolicyEvidence(
        policy_id="KB-03",
        title="Laptop Replacement",
        content="Laptops are eligible for replacement after 3 years of service, or earlier in case of verified hardware failure. Requests must be raised at least 2 weeks in advance of intended replacement.",
        relevance=0.95,
    )


@pytest.fixture
def asset01_policy():
    """ASSET-01: Asset Management Policy"""
    return PolicyEvidence(
        policy_id="ASSET-01",
        title="Asset Management Policy",
        content="All company-issued hardware, including laptops and monitors, follows a standard 4-year refresh cycle from date of issue. Early replacement outside this cycle requires Finance sign-off in addition to IT approval.",
        relevance=0.92,
    )


@pytest.fixture
def kb04_policy():
    """KB-04: Software Installation"""
    return PolicyEvidence(
        policy_id="KB-04",
        title="Software Installation Requests",
        content="Standard software (listed in the approved catalog) can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days.",
        relevance=0.93,
    )


@pytest.fixture
def kb05_policy():
    """KB-05: Printer Troubleshooting"""
    return PolicyEvidence(
        policy_id="KB-05",
        title="Printer Troubleshooting",
        content="For printer issues, first check the printer queue and restart the print spooler. If the issue persists after restart, log a ticket with the printer's asset tag.",
        relevance=0.91,
    )


@pytest.fixture
def kb06_policy():
    """KB-06: Email Mailbox Quota"""
    return PolicyEvidence(
        policy_id="KB-06",
        title="Email Mailbox Quota",
        content="Default mailbox quota is 25GB. Employees nearing quota should archive old mail. Quota increases beyond 25GB require manager approval and are capped at 50GB.",
        relevance=0.94,
    )


@pytest.fixture
def kb07_policy():
    """KB-07: Guest Wi-Fi Access"""
    return PolicyEvidence(
        policy_id="KB-07",
        title="Guest Wi-Fi Access",
        content="Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee from the front-desk kiosk. No IT ticket required.",
        relevance=0.96,
    )


@pytest.fixture
def kb08_policy():
    """KB-08: Expense Software Access"""
    return PolicyEvidence(
        policy_id="KB-08",
        title="Expense Software Access",
        content="Access to the expense management tool is granted by Finance, not IT. IT can only assist with login/technical issues once an account already exists.",
        relevance=0.92,
    )


@pytest.fixture
def kb09_policy():
    """KB-09: Security Incident Reporting"""
    return PolicyEvidence(
        policy_id="KB-09",
        title="Security Incident Reporting",
        content="Any suspected phishing email, malware, or unauthorized access attempt must be reported to security@veridian-corp.example immediately and should not be forwarded to other employees.",
        relevance=0.97,
    )


@pytest.fixture
def kb10_policy():
    """KB-10: Work-From-Home Equipment"""
    return PolicyEvidence(
        policy_id="KB-10",
        title="Work-From-Home Equipment",
        content="Employees working remotely more than 3 days/week are eligible for a one-time home office equipment allowance (chair, monitor). Requires manager sign-off and Finance processing — IT only handles the equipment shipping request once approved.",
        relevance=0.93,
    )


# ============================================================================
# KB-01: Password Reset Tests
# ============================================================================

def test_password_reset_normal(kb01_policy):
    """Test normal password reset via self-service portal."""
    facts = ExtractedFacts(
        intent="password_reset",
        entities={"issue": "forgot password"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb01_policy], [])
    
    assert decision.decision == "RESOLVE"
    assert "self-service" in decision.reason.lower()
    assert "KB-01" in decision.sources
    assert "no approval" in decision.reason.lower()


def test_password_reset_locked_out(kb01_policy):
    """Test password reset when locked out after >5 failed attempts (REQ-03 scenario)."""
    facts = ExtractedFacts(
        intent="account_locked",
        entities={"failed_attempts": 6, "issue": "locked out, tried 6 times"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb01_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "locked" in decision.reason.lower()
    assert "manual" in decision.reason.lower()
    assert "KB-01" in decision.sources


# ============================================================================
# KB-02: VPN Access Tests
# ============================================================================

def test_vpn_full_time_employee(kb02_policy):
    """Test VPN access for full-time employee (automatic)."""
    facts = ExtractedFacts(
        intent="vpn_access",
        entities={"employee_type": "full-time"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb02_policy], [])
    
    assert decision.decision == "RESOLVE"
    assert "automatically" in decision.reason.lower()
    assert "KB-02" in decision.sources


def test_vpn_contractor(kb02_policy):
    """Test VPN access for contractor (requires manager approval) (REQ-11 scenario)."""
    facts = ExtractedFacts(
        intent="vpn_access_contractor",
        entities={"employee_type": "contractor"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb02_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "contractor" in decision.reason.lower()
    assert "manager approval" in decision.reason.lower()
    assert "KB-02" in decision.sources


def test_vpn_expired_credentials(kb02_policy):
    """Test VPN with expired credentials (REQ-05 scenario)."""
    facts = ExtractedFacts(
        intent="vpn_issue",
        entities={"issue": "credentials expired, stopped working this morning"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb02_policy], [])
    
    assert decision.decision == "RESOLVE"
    assert "renew" in decision.reason.lower() or "90 days" in decision.reason.lower()
    assert "KB-02" in decision.sources


def test_vpn_employee_type_unknown(kb02_policy):
    """Test VPN when employee type is unknown."""
    facts = ExtractedFacts(
        intent="vpn_access",
        entities={},
        missing_information=["employee_type"],
    )
    
    decision = evaluate_decision(facts, [kb02_policy], [])
    
    assert decision.decision == "FOLLOW_UP"
    assert "employee type" in decision.reason.lower() or "full-time" in decision.reason.lower() or "contractor" in decision.reason.lower()
    assert "KB-02" in decision.sources


# ============================================================================
# KB-03 + ASSET-01: Laptop Replacement Tests
# ============================================================================

def test_laptop_dead_3_5_years_unverified(kb03_policy, asset01_policy):
    """Test laptop dead, 3.5 years old, failure NOT verified (REQ-01 scenario)."""
    facts = ExtractedFacts(
        intent="laptop_replacement",
        entities={"laptop_age_years": 3.5, "issue": "won't turn on at all, completely dead", "verified_failure": False},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb03_policy, asset01_policy], [])
    
    # Reported but not verified → FOLLOW_UP
    assert decision.decision == "FOLLOW_UP"
    assert "verif" in decision.reason.lower()
    assert "KB-03" in decision.sources


def test_laptop_4_years_normal_refresh(kb03_policy, asset01_policy):
    """Test laptop >=4 years old (normal refresh cycle)."""
    facts = ExtractedFacts(
        intent="laptop_replacement",
        entities={"laptop_age_years": 4.2, "issue": "requesting replacement, laptop is old"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb03_policy, asset01_policy], [])
    
    assert decision.decision == "RESOLVE"
    assert "4-year" in decision.reason.lower() or "refresh cycle" in decision.reason.lower()
    assert "2 weeks" in decision.reason.lower()
    assert "KB-03" in decision.sources
    assert "ASSET-01" in decision.sources


def test_laptop_3_5_years_verified_failure(kb03_policy, asset01_policy):
    """Test laptop 3.5 years with VERIFIED hardware failure - still needs Finance per ASSET-01."""
    facts = ExtractedFacts(
        intent="laptop_replacement",
        entities={"laptop_age_years": 3.5, "issue": "dead, won't turn on", "verified_failure": True},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb03_policy, asset01_policy], [])
    
    # Verified failure at 3.5 years → eligible per KB-03
    # BUT <4 years → early replacement per ASSET-01 → requires Finance sign-off
    assert decision.decision == "ESCALATE"
    assert "verified" in decision.reason.lower()
    assert "finance" in decision.reason.lower()
    assert "KB-03" in decision.sources
    assert "ASSET-01" in decision.sources


def test_laptop_2_years(kb03_policy, asset01_policy):
    """Test laptop <3 years old (not eligible) (REQ-13 scenario)."""
    facts = ExtractedFacts(
        intent="laptop_issue",
        entities={"laptop_age_years": 2.0, "issue": "screen flickering, might need fix not replacement"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb03_policy, asset01_policy], [])
    
    # <3 years → not eligible → requires Finance sign-off
    assert decision.decision == "ESCALATE"
    assert "3 years" in decision.reason.lower() or "finance" in decision.reason.lower()
    assert "KB-03" in decision.sources or "ASSET-01" in decision.sources


def test_laptop_age_missing(kb03_policy, asset01_policy):
    """Test laptop replacement with missing age info."""
    facts = ExtractedFacts(
        intent="laptop_replacement",
        entities={"issue": "laptop won't turn on"},
        missing_information=["laptop_age_years"],
    )
    
    decision = evaluate_decision(facts, [kb03_policy, asset01_policy], [])
    
    assert decision.decision == "FOLLOW_UP"
    assert "age" in decision.reason.lower()
    assert "KB-03" in decision.sources or "ASSET-01" in decision.sources


# ============================================================================
# KB-04: Software Installation Tests
# ============================================================================

def test_software_in_catalog(kb04_policy):
    """Test software installation from approved catalog."""
    facts = ExtractedFacts(
        intent="software_install",
        entities={"software_name": "Approved Tool", "in_catalog": True},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb04_policy], [])
    
    assert decision.decision == "RESOLVE"
    assert "catalog" in decision.reason.lower() or "self-install" in decision.reason.lower()
    assert "KB-04" in decision.sources


def test_software_not_in_catalog(kb04_policy):
    """Test software NOT in catalog (requires Security review) (REQ-04, REQ-14 scenario)."""
    facts = ExtractedFacts(
        intent="software_install",
        entities={"software_name": "data-analysis tool", "in_catalog": False},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb04_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "security review" in decision.reason.lower()
    assert "3–5 business days" in decision.reason.lower() or "3-5" in decision.reason.lower()
    assert "KB-04" in decision.sources


def test_software_catalog_status_unknown(kb04_policy):
    """Test software with unknown catalog status."""
    facts = ExtractedFacts(
        intent="software_install",
        entities={"software_name": "Some Tool"},
        missing_information=["in_catalog"],
    )
    
    decision = evaluate_decision(facts, [kb04_policy], [])
    
    assert decision.decision == "FOLLOW_UP"
    assert "catalog" in decision.reason.lower()
    assert "KB-04" in decision.sources


def test_software_name_missing(kb04_policy):
    """Test software installation with missing software name."""
    facts = ExtractedFacts(
        intent="software_install",
        entities={},
        missing_information=["software_name"],
    )
    
    decision = evaluate_decision(facts, [kb04_policy], [])
    
    assert decision.decision == "FOLLOW_UP"
    assert "software" in decision.reason.lower()
    assert "KB-04" in decision.sources


# ============================================================================
# KB-05: Printer Troubleshooting Tests
# ============================================================================

def test_printer_troubleshooting_not_attempted(kb05_policy):
    """Test printer issue, troubleshooting not yet attempted (REQ-06 scenario)."""
    facts = ExtractedFacts(
        intent="printer_issue",
        entities={"issue": "paper jam error", "troubleshooting_attempted": False},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb05_policy], [])
    
    assert decision.decision == "RESOLVE"
    assert "queue" in decision.reason.lower() or "spooler" in decision.reason.lower()
    assert "KB-05" in decision.sources


def test_printer_troubleshooting_done_with_asset_tag(kb05_policy):
    """Test printer issue, troubleshooting done, has asset tag."""
    facts = ExtractedFacts(
        intent="printer_issue",
        entities={"issue": "still showing error", "troubleshooting_attempted": True, "asset_tag": "PRINTER-3F-001"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb05_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "asset tag" in decision.reason.lower()
    assert "KB-05" in decision.sources


def test_printer_troubleshooting_done_no_asset_tag(kb05_policy):
    """Test printer issue, troubleshooting done, asset tag missing."""
    facts = ExtractedFacts(
        intent="printer_issue",
        entities={"issue": "still not working", "troubleshooting_attempted": True},
        missing_information=["asset_tag"],
    )
    
    decision = evaluate_decision(facts, [kb05_policy], [])
    
    assert decision.decision == "FOLLOW_UP"
    assert "asset tag" in decision.reason.lower()
    assert "KB-05" in decision.sources


# ============================================================================
# KB-06: Email Mailbox Quota Tests
# ============================================================================

def test_mailbox_full_archive(kb06_policy):
    """Test mailbox full, should archive (REQ-09 scenario)."""
    facts = ExtractedFacts(
        intent="mailbox_full",
        entities={"issue": "mailbox is full, can't send emails"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb06_policy], [])
    
    assert decision.decision == "RESOLVE"
    assert "archive" in decision.reason.lower()
    assert "25gb" in decision.reason.lower()
    assert "KB-06" in decision.sources


def test_mailbox_quota_increase_30gb(kb06_policy):
    """Test mailbox quota increase to 30GB (requires manager approval)."""
    facts = ExtractedFacts(
        intent="mailbox_quota_increase",
        entities={"requested_quota_gb": 30, "current_quota_gb": 25},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb06_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "manager approval" in decision.reason.lower()
    assert "KB-06" in decision.sources


def test_mailbox_quota_increase_60gb(kb06_policy):
    """Test mailbox quota increase beyond 50GB cap."""
    facts = ExtractedFacts(
        intent="mailbox_quota_increase",
        entities={"requested_quota_gb": 60},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb06_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "50gb" in decision.reason.lower() and "maximum" in decision.reason.lower()
    assert "KB-06" in decision.sources


# ============================================================================
# KB-07: Guest Wi-Fi Tests
# ============================================================================

def test_guest_wifi_24_hours(kb07_policy):
    """Test guest WiFi for 24 hours (standard) (REQ-02 scenario)."""
    facts = ExtractedFacts(
        intent="guest_wifi",
        entities={"duration_hours": 24},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb07_policy], [])
    
    assert decision.decision == "RESOLVE"
    assert "24 hours" in decision.reason.lower() or "24 hour" in decision.reason.lower()
    assert "kiosk" in decision.reason.lower()
    assert "no it ticket" in decision.reason.lower()
    assert "KB-07" in decision.sources


def test_guest_wifi_beyond_24_hours(kb07_policy):
    """Test guest WiFi beyond 24 hours (not supported by policy)."""
    facts = ExtractedFacts(
        intent="guest_wifi_extended",
        entities={"duration_hours": 168},  # 7 days
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb07_policy], [])
    
    # Beyond 24 hours is not supported by KB-07
    assert decision.decision == "ESCALATE"
    assert "24" in decision.reason.lower()
    assert "KB-07" in decision.sources


# ============================================================================
# KB-08: Expense Software Access Tests
# ============================================================================

def test_expense_software_login_issue(kb08_policy):
    """Test expense software login issue (REQ-12 scenario) - needs account_exists info."""
    facts = ExtractedFacts(
        intent="expense_tool_issue",
        entities={"issue": "can't log in, invalid credentials", "account_exists": True},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb08_policy], [])
    
    assert decision.decision == "RESOLVE"
    assert "login" in decision.reason.lower() or "technical" in decision.reason.lower()
    assert "KB-08" in decision.sources


def test_expense_software_access_request(kb08_policy):
    """Test expense software access request (Finance, not IT)."""
    facts = ExtractedFacts(
        intent="expense_tool_access",
        entities={"issue": "need access to expense tool"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb08_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "finance" in decision.reason.lower()
    assert "not it" in decision.reason.lower()
    assert "KB-08" in decision.sources


# ============================================================================
# KB-09: Security Incident Tests
# ============================================================================

def test_security_phishing_forwarding(kb09_policy):
    """Test phishing email with user planning to forward it (REQ-08 scenario)."""
    facts = ExtractedFacts(
        intent="security_phishing",
        entities={"issue": "phishing email", "user_action": "forwarding to teammates to check"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb09_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "security@veridian-corp.example" in decision.reason.lower()
    assert "do not forward" in decision.reason.lower() or "should not" in decision.reason.lower()
    assert "KB-09" in decision.sources


def test_security_malware(kb09_policy):
    """Test suspected malware."""
    facts = ExtractedFacts(
        intent="security_malware",
        entities={"issue": "suspected malware"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb09_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "security@veridian-corp.example" in decision.reason.lower()
    assert "KB-09" in decision.sources


def test_security_unauthorized_access(kb09_policy):
    """Test unauthorized access attempt."""
    facts = ExtractedFacts(
        intent="security_unauthorized_access",
        entities={"issue": "unauthorized access attempt"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb09_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "security@veridian-corp.example" in decision.reason.lower()
    assert "KB-09" in decision.sources


# ============================================================================
# KB-10: Work-From-Home Equipment Tests
# ============================================================================

def test_wfh_equipment_4_days_per_week(kb10_policy):
    """Test WFH equipment for 4 days/week (eligible) (REQ-07 scenario)."""
    facts = ExtractedFacts(
        intent="wfh_equipment",
        entities={"remote_days_per_week": 4},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb10_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "eligible" in decision.reason.lower()
    assert "manager sign-off" in decision.reason.lower() and "finance" in decision.reason.lower()
    assert "KB-10" in decision.sources


def test_wfh_equipment_2_days_per_week(kb10_policy):
    """Test WFH equipment for 2 days/week (not eligible)."""
    facts = ExtractedFacts(
        intent="wfh_equipment",
        entities={"remote_days_per_week": 2},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb10_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "more than 3 days" in decision.reason.lower() or ">3" in decision.reason.lower() or "eligib" in decision.reason.lower()
    assert "KB-10" in decision.sources


def test_wfh_equipment_days_unknown(kb10_policy):
    """Test WFH equipment with unknown remote days."""
    facts = ExtractedFacts(
        intent="wfh_equipment",
        entities={},
        missing_information=["remote_days_per_week"],
    )
    
    decision = evaluate_decision(facts, [kb10_policy], [])
    
    assert decision.decision == "FOLLOW_UP"
    assert "days" in decision.reason.lower() and "week" in decision.reason.lower()
    assert "KB-10" in decision.sources


# ============================================================================
# Unsupported Request Tests
# ============================================================================

def test_admin_access_unsupported():
    """Test admin access request (REQ-10 scenario - NO policy for this)."""
    facts = ExtractedFacts(
        intent="admin_access",
        entities={"server": "finance reporting server"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [], [])
    
    # No policy covers admin access → FOLLOW_UP or ESCALATE
    assert decision.decision in ["FOLLOW_UP", "ESCALATE"]
    assert "not covered" in decision.reason.lower() or "not match" in decision.reason.lower()


def test_vague_request():
    """Test vague request (REQ-15 scenario) → FOLLOW_UP."""
    facts = ExtractedFacts(
        intent="unclear_request",
        entities={"issue": "hey can you help, its not working"},
        missing_information=["what_is_not_working"],
    )
    
    decision = evaluate_decision(facts, [], [])
    
    # Vague request → FOLLOW_UP
    assert decision.decision == "FOLLOW_UP"
    assert "unclear" in decision.reason.lower() or "incomplete" in decision.reason.lower()


# ============================================================================
# Ticket Context Tests
# ============================================================================

def test_decision_with_ticket_context(kb06_policy):
    """Test that ticket history provides context but doesn't override policy."""
    facts = ExtractedFacts(
        intent="mailbox_quota_increase",
        entities={"requested_quota_gb": 40},
        missing_information=[],
    )
    
    # TK-1045 shows 100GB was granted (historical), but policy caps at 50GB
    tickets = [
        TicketContext(
            ticket_id="TK-1045",
            employee="Someone Else",
            issue_summary="Mailbox quota increased to 100GB",
            status="Approved (closed)",
            is_active=False,
        )
    ]
    
    decision = evaluate_decision(facts, [kb06_policy], tickets)
    
    # Policy MUST NOT be overridden by historical ticket
    assert decision.decision == "ESCALATE"
    assert "manager approval" in decision.reason.lower()
    assert "KB-06" in decision.sources
    # Should still respect 50GB cap even though TK-1045 shows 100GB


def test_decision_with_active_ticket(kb05_policy):
    """Test decision with active ticket (human handling already underway)."""
    facts = ExtractedFacts(
        intent="printer_issue",
        entities={"issue": "paper jam", "troubleshooting_attempted": False},
        missing_information=[],
    )
    
    tickets = [
        TicketContext(
            ticket_id="TK-1047",
            employee="Same Employee",
            issue_summary="Printer issue, technician assigned",
            status="Investigating — technician assigned",
            is_active=True,
        )
    ]
    
    decision = evaluate_decision(facts, [kb05_policy], tickets)
    
    # Decision should still follow policy
    assert decision.decision == "RESOLVE"
    assert "KB-05" in decision.sources
    # Active ticket provides context but doesn't change the policy decision


# ============================================================================
# Integration Tests
# ============================================================================

def test_decision_with_full_context(kb01_policy):
    """Test decision with facts + policies + tickets."""
    facts = ExtractedFacts(
        intent="password_reset",
        entities={"issue": "forgot password"},
        missing_information=[],
    )
    
    tickets = [
        TicketContext(
            ticket_id="TK-1042",
            employee="Previous User",
            issue_summary="Password reset",
            status="Resolved (closed)",
            is_active=False,
        )
    ]
    
    decision = evaluate_decision(facts, [kb01_policy], tickets)
    
    assert decision.decision == "RESOLVE"
    assert len(decision.relevant_policies) > 0
    assert len(decision.relevant_tickets) > 0
    assert decision.confidence > 0.8
    assert "KB-01" in decision.sources


def test_confidence_with_missing_information(kb03_policy, asset01_policy):
    """Test that confidence decreases with missing information."""
    facts_complete = ExtractedFacts(
        intent="laptop_replacement",
        entities={"laptop_age_years": 4.0, "issue": "requesting replacement"},
        missing_information=[],
    )
    
    facts_incomplete = ExtractedFacts(
        intent="laptop_replacement",
        entities={"issue": "requesting replacement"},
        missing_information=["laptop_age_years"],
    )
    
    decision_complete = evaluate_decision(facts_complete, [kb03_policy, asset01_policy], [])
    decision_incomplete = evaluate_decision(facts_incomplete, [kb03_policy, asset01_policy], [])
    
    # Complete facts should have higher confidence
    assert decision_complete.confidence >= decision_incomplete.confidence



# ============================================================================
# Policy Evidence Requirement Tests
# ============================================================================

def test_password_request_without_kb01_evidence():
    """Test password request without KB-01 evidence - rule should not apply."""
    facts = ExtractedFacts(
        intent="password_reset",
        entities={"issue": "forgot password"},
        missing_information=[],
    )
    
    # No KB-01 in policies → unsupported
    decision = evaluate_decision(facts, [], [])
    
    assert decision.decision in ["FOLLOW_UP", "ESCALATE"]
    assert "KB-01" not in decision.sources


def test_password_request_with_wrong_policy_evidence():
    """Test password request with wrong policy evidence (KB-06 instead of KB-01)."""
    facts = ExtractedFacts(
        intent="password_reset",
        entities={"issue": "forgot password"},
        missing_information=[],
    )
    
    # Only KB-06 provided, not KB-01
    wrong_policy = PolicyEvidence(
        policy_id="KB-06",
        title="Email Mailbox Quota",
        content="Default mailbox quota is 25GB...",
        relevance=0.8,
    )
    
    decision = evaluate_decision(facts, [wrong_policy], [])
    
    # KB-01 rule should not execute without KB-01 evidence
    assert decision.decision in ["FOLLOW_UP", "ESCALATE"]
    assert "KB-01" not in decision.sources


def test_laptop_3_5_years_verified_failure_with_asset01(kb03_policy, asset01_policy):
    """Test laptop 3.5 years with VERIFIED failure - still needs Finance per ASSET-01."""
    facts = ExtractedFacts(
        intent="laptop_replacement",
        entities={"laptop_age_years": 3.5, "issue": "dead, won't turn on", "verified_failure": True},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb03_policy, asset01_policy], [])
    
    # Verified failure at 3.5 years → still <4 years → requires Finance per ASSET-01
    assert decision.decision == "ESCALATE"
    assert "verified" in decision.reason.lower()
    assert "finance" in decision.reason.lower()
    assert "KB-03" in decision.sources
    assert "ASSET-01" in decision.sources


def test_laptop_3_5_years_unverified_failure_followup(kb03_policy, asset01_policy):
    """Test laptop 3.5 years with UNVERIFIED failure → FOLLOW_UP."""
    facts = ExtractedFacts(
        intent="laptop_replacement",
        entities={"laptop_age_years": 3.5, "issue": "dead, won't turn on", "verified_failure": False},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb03_policy, asset01_policy], [])
    
    # Reported but not verified → FOLLOW_UP
    assert decision.decision == "FOLLOW_UP"
    assert "verif" in decision.reason.lower()
    assert "not yet verified" in decision.reason.lower()
    assert "KB-03" in decision.sources


def test_expense_login_account_exists_true(kb08_policy):
    """Test expense login issue with account_exists=True → RESOLVE."""
    facts = ExtractedFacts(
        intent="expense_tool_issue",
        entities={"issue": "can't log in, invalid credentials", "account_exists": True},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb08_policy], [])
    
    assert decision.decision == "RESOLVE"
    assert "login" in decision.reason.lower() or "technical" in decision.reason.lower()
    assert "KB-08" in decision.sources


def test_expense_login_account_exists_false(kb08_policy):
    """Test expense login issue with account_exists=False → ESCALATE to Finance."""
    facts = ExtractedFacts(
        intent="expense_tool_issue",
        entities={"issue": "can't log in, invalid credentials", "account_exists": False},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [kb08_policy], [])
    
    assert decision.decision == "ESCALATE"
    assert "finance" in decision.reason.lower()
    assert "KB-08" in decision.sources


def test_expense_login_account_exists_unknown(kb08_policy):
    """Test expense login issue with account_exists unknown → FOLLOW_UP."""
    facts = ExtractedFacts(
        intent="expense_tool_issue",
        entities={"issue": "can't log in, invalid credentials"},
        missing_information=["account_exists"],
    )
    
    decision = evaluate_decision(facts, [kb08_policy], [])
    
    assert decision.decision == "FOLLOW_UP"
    assert "verify" in decision.reason.lower() or "account exists" in decision.reason.lower()
    assert "KB-08" in decision.sources


def test_policy_evidence_mismatch_laptop_without_kb03():
    """Test laptop request without KB-03 evidence."""
    facts = ExtractedFacts(
        intent="laptop_replacement",
        entities={"laptop_age_years": 4.0, "issue": "requesting replacement"},
        missing_information=[],
    )
    
    # No KB-03 provided
    decision = evaluate_decision(facts, [], [])
    
    # Without KB-03, laptop rule should not execute
    assert decision.decision in ["FOLLOW_UP", "ESCALATE"]
    assert "KB-03" not in decision.sources


def test_admin_access_unsupported_no_invention():
    """Test admin access - ensure no authorization policy is invented."""
    facts = ExtractedFacts(
        intent="admin_access",
        entities={"server": "finance reporting server"},
        missing_information=[],
    )
    
    decision = evaluate_decision(facts, [], [])
    
    # No policy covers admin access → should escalate/follow-up, not invent policy
    assert decision.decision in ["FOLLOW_UP", "ESCALATE"]
    assert "not covered" in decision.reason.lower() or "not match" in decision.reason.lower() or "does not match" in decision.reason.lower()
    assert len(decision.sources) == 0  # No policy sources


def test_vague_request_follow_up():
    """Test vague request → FOLLOW_UP (not automatic escalation)."""
    facts = ExtractedFacts(
        intent="unclear_request",
        entities={"issue": "hey can you help, its not working"},
        missing_information=["what_is_not_working"],
    )
    
    decision = evaluate_decision(facts, [], [])
    
    # Vague request with missing info → FOLLOW_UP
    assert decision.decision == "FOLLOW_UP"
    assert "unclear" in decision.reason.lower() or "incomplete" in decision.reason.lower()
